image: docker:19.03.1

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.1-dind

before_script:
  - docker info

test:
  stage: test
  script:
    - docker build -t dubzland-dhcpd -f tests/Dockerfile .
    - docker run dubzland-dhcpd /usr/src/dubzland-dhcpd/tests/run_tests.sh
