---
- import_tasks: variables.yml
- import_tasks: packages.yml
- import_tasks: configuration.yml

- meta: flush_handlers

- name: ensure dhcpd is running
  service:
    name: "{{ dubzland_dhcpd_service }}"
    state: started
