---
- import_tasks: variables.yml
- import_tasks: packages.yml
- import_tasks: configuration.yml

- meta: flush_handlers

- name: dump the dhcpd journal
  command: journalctl -u isc-dhcp-server --no-pager
  register: dhcp_server_output
  changed_when: False

- name: print the journal
  debug:
    msg: "{{ dhcp_server_output.stdout_lines }}"

- name: ensure dhcpd is running
  service:
    name: "{{ dubzland_dhcpd_service }}"
    state: started
