---
- name: enable dhcpd
  service:
    name: "{{ dubzland_dhcpd_service }}"
    enabled: yes

- name: restart dhcpd
  command: dhcpd -t --no-pid
  notify: restart dhcpd (real)

- name: restart dhcpd (real)
  service:
    name: "{{ dubzland_dhcpd_service }}"
    state: restarted
  failed_when: False
