---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-dhcpd
      vars:
        dubzland_dhcpd_interfaces:
          - eth0
        dubzland_dhcpd_subnets:
          - address: 172.17.0.0/24
            pools:
              - range: 172.17.0.101 172.17.0.200
